// AUTO-GENERATED by scripts/update-registries.js — do not edit manually.
// Run: node scripts/update-registries.js
import { notFound } from 'next/navigation'
import ExamShell from '@/components/exam/ExamShell'
import { questions as physics_nov_2023Questions, paperMeta as physics_nov_2023Meta } from '@/data/papers/physics-nov-2023/questions'
import { questions as physics_may_2025Questions, paperMeta as physics_may_2025Meta } from '@/data/papers/physics-may-2025/questions'
import { questions as physics_nov_2016Questions, paperMeta as physics_nov_2016Meta } from '@/data/papers/physics-nov-2016/questions'
import { questions as physics_nov_2024Questions, paperMeta as physics_nov_2024Meta } from '@/data/papers/physics-nov-2024/questions'
import { questions as physics_practice_v1Questions, paperMeta as physics_practice_v1Meta } from '@/data/papers/physics-practice-v1/questions'
import { questions as physics_may_2024Questions, paperMeta as physics_may_2024Meta } from '@/data/papers/physics-may-2024/questions'
import { questions as physics_nov_2022Questions, paperMeta as physics_nov_2022Meta } from '@/data/papers/physics-nov-2022/questions'
import { questions as physics_may_2023Questions, paperMeta as physics_may_2023Meta } from '@/data/papers/physics-may-2023/questions'
import { questions as physics_may_2022Questions, paperMeta as physics_may_2022Meta } from '@/data/papers/physics-may-2022/questions'
import { questions as physics_nov_2021Questions, paperMeta as physics_nov_2021Meta } from '@/data/papers/physics-nov-2021/questions'
import { questions as physics_may_2021Questions, paperMeta as physics_may_2021Meta } from '@/data/papers/physics-may-2021/questions'
import { questions as physics_nov_2020Questions, paperMeta as physics_nov_2020Meta } from '@/data/papers/physics-nov-2020/questions'
import { questions as physics_nov_2019Questions, paperMeta as physics_nov_2019Meta } from '@/data/papers/physics-nov-2019/questions'
import { questions as physics_may_2019Questions, paperMeta as physics_may_2019Meta } from '@/data/papers/physics-may-2019/questions'
import { questions as physics_nov_2018Questions, paperMeta as physics_nov_2018Meta } from '@/data/papers/physics-nov-2018/questions'
import { questions as physics_may_2018Questions, paperMeta as physics_may_2018Meta } from '@/data/papers/physics-may-2018/questions'
import { questions as physics_nov_2017Questions, paperMeta as physics_nov_2017Meta } from '@/data/papers/physics-nov-2017/questions'
import { questions as physics_may_2017Questions, paperMeta as physics_may_2017Meta } from '@/data/papers/physics-may-2017/questions'
import type { Question } from '@/lib/types'

interface PageProps {
  params: { paperId: string }
}

interface PaperMeta {
  id: string
  subject: string
  session: string
  year: number
  totalMarks: number
  durationMinutes: number
  criteria: readonly string[]
}

const PAPERS: Record<string, { questions: Question[]; meta: PaperMeta }> = {
  'physics-nov-2023': { questions: physics_nov_2023Questions, meta: physics_nov_2023Meta },
  'physics-may-2025': { questions: physics_may_2025Questions, meta: physics_may_2025Meta },
  'physics-nov-2016': { questions: physics_nov_2016Questions, meta: physics_nov_2016Meta },
  'physics-nov-2024': { questions: physics_nov_2024Questions, meta: physics_nov_2024Meta },
  'physics-practice-v1': { questions: physics_practice_v1Questions, meta: physics_practice_v1Meta },
  'physics-may-2024': { questions: physics_may_2024Questions, meta: physics_may_2024Meta },
  'physics-nov-2022': { questions: physics_nov_2022Questions, meta: physics_nov_2022Meta },
  'physics-may-2023': { questions: physics_may_2023Questions, meta: physics_may_2023Meta },
  'physics-may-2022': { questions: physics_may_2022Questions, meta: physics_may_2022Meta },
  'physics-nov-2021': { questions: physics_nov_2021Questions, meta: physics_nov_2021Meta },
  'physics-may-2021': { questions: physics_may_2021Questions, meta: physics_may_2021Meta },
  'physics-nov-2020': { questions: physics_nov_2020Questions, meta: physics_nov_2020Meta },
  'physics-nov-2019': { questions: physics_nov_2019Questions, meta: physics_nov_2019Meta },
  'physics-may-2019': { questions: physics_may_2019Questions, meta: physics_may_2019Meta },
  'physics-nov-2018': { questions: physics_nov_2018Questions, meta: physics_nov_2018Meta },
  'physics-may-2018': { questions: physics_may_2018Questions, meta: physics_may_2018Meta },
  'physics-nov-2017': { questions: physics_nov_2017Questions, meta: physics_nov_2017Meta },
  'physics-may-2017': { questions: physics_may_2017Questions, meta: physics_may_2017Meta },
}

export default function ExamPage({ params }: PageProps) {
  const { paperId } = params
  const paper = PAPERS[paperId]

  if (!paper) {
    notFound()
  }

  return <ExamShell questions={paper.questions} paperId={paperId} />
}
