// AUTO-GENERATED by scripts/update-registries.js — do not edit manually.
// Run: node scripts/update-registries.js
import { notFound } from 'next/navigation'
import ExamShell from '@/components/exam/ExamShell'
import { questions as physics_nov_2023Questions, paperMeta as physics_nov_2023Meta } from '@/data/papers/physics-nov-2023/questions'
import { questions as biology_may_2016Questions, paperMeta as biology_may_2016Meta } from '@/data/papers/biology-may-2016/questions'
import { questions as biology_may_2017Questions, paperMeta as biology_may_2017Meta } from '@/data/papers/biology-may-2017/questions'
import { questions as biology_may_2018Questions, paperMeta as biology_may_2018Meta } from '@/data/papers/biology-may-2018/questions'
import { questions as biology_may_2019Questions, paperMeta as biology_may_2019Meta } from '@/data/papers/biology-may-2019/questions'
import { questions as biology_may_2021Questions, paperMeta as biology_may_2021Meta } from '@/data/papers/biology-may-2021/questions'
import { questions as biology_may_2022Questions, paperMeta as biology_may_2022Meta } from '@/data/papers/biology-may-2022/questions'
import { questions as biology_may_2023Questions, paperMeta as biology_may_2023Meta } from '@/data/papers/biology-may-2023/questions'
import { questions as biology_may_2024Questions, paperMeta as biology_may_2024Meta } from '@/data/papers/biology-may-2024/questions'
import { questions as biology_may_2025Questions, paperMeta as biology_may_2025Meta } from '@/data/papers/biology-may-2025/questions'
import { questions as biology_may_2025_v1Questions, paperMeta as biology_may_2025_v1Meta } from '@/data/papers/biology-may-2025-v1/questions'
import { questions as biology_may_2025_v2Questions, paperMeta as biology_may_2025_v2Meta } from '@/data/papers/biology-may-2025-v2/questions'
import { questions as biology_nov_2016Questions, paperMeta as biology_nov_2016Meta } from '@/data/papers/biology-nov-2016/questions'
import { questions as biology_nov_2017Questions, paperMeta as biology_nov_2017Meta } from '@/data/papers/biology-nov-2017/questions'
import { questions as biology_nov_2018Questions, paperMeta as biology_nov_2018Meta } from '@/data/papers/biology-nov-2018/questions'
import { questions as biology_nov_2019Questions, paperMeta as biology_nov_2019Meta } from '@/data/papers/biology-nov-2019/questions'
import { questions as biology_nov_2020Questions, paperMeta as biology_nov_2020Meta } from '@/data/papers/biology-nov-2020/questions'
import { questions as biology_nov_2021Questions, paperMeta as biology_nov_2021Meta } from '@/data/papers/biology-nov-2021/questions'
import { questions as biology_nov_2022Questions, paperMeta as biology_nov_2022Meta } from '@/data/papers/biology-nov-2022/questions'
import { questions as biology_nov_2023Questions, paperMeta as biology_nov_2023Meta } from '@/data/papers/biology-nov-2023/questions'
import { questions as biology_nov_2024Questions, paperMeta as biology_nov_2024Meta } from '@/data/papers/biology-nov-2024/questions'
import { questions as chemistry_may_2016Questions, paperMeta as chemistry_may_2016Meta } from '@/data/papers/chemistry-may-2016/questions'
import { questions as chemistry_may_2016_v1Questions, paperMeta as chemistry_may_2016_v1Meta } from '@/data/papers/chemistry-may-2016-v1/questions'
import { questions as chemistry_may_2016_v2Questions, paperMeta as chemistry_may_2016_v2Meta } from '@/data/papers/chemistry-may-2016-v2/questions'
import { questions as chemistry_may_2017Questions, paperMeta as chemistry_may_2017Meta } from '@/data/papers/chemistry-may-2017/questions'
import { questions as chemistry_may_2017_v1Questions, paperMeta as chemistry_may_2017_v1Meta } from '@/data/papers/chemistry-may-2017-v1/questions'
import { questions as chemistry_may_2017_v2Questions, paperMeta as chemistry_may_2017_v2Meta } from '@/data/papers/chemistry-may-2017-v2/questions'
import { questions as chemistry_may_2018Questions, paperMeta as chemistry_may_2018Meta } from '@/data/papers/chemistry-may-2018/questions'
import { questions as chemistry_may_2018_v1Questions, paperMeta as chemistry_may_2018_v1Meta } from '@/data/papers/chemistry-may-2018-v1/questions'
import { questions as chemistry_may_2018_v2Questions, paperMeta as chemistry_may_2018_v2Meta } from '@/data/papers/chemistry-may-2018-v2/questions'
import { questions as chemistry_may_2019Questions, paperMeta as chemistry_may_2019Meta } from '@/data/papers/chemistry-may-2019/questions'
import { questions as chemistry_may_2019_v1Questions, paperMeta as chemistry_may_2019_v1Meta } from '@/data/papers/chemistry-may-2019-v1/questions'
import { questions as chemistry_may_2019_v2Questions, paperMeta as chemistry_may_2019_v2Meta } from '@/data/papers/chemistry-may-2019-v2/questions'
import { questions as chemistry_may_2021Questions, paperMeta as chemistry_may_2021Meta } from '@/data/papers/chemistry-may-2021/questions'
import { questions as chemistry_may_2021_v1Questions, paperMeta as chemistry_may_2021_v1Meta } from '@/data/papers/chemistry-may-2021-v1/questions'
import { questions as chemistry_may_2021_v2Questions, paperMeta as chemistry_may_2021_v2Meta } from '@/data/papers/chemistry-may-2021-v2/questions'
import { questions as chemistry_may_2022Questions, paperMeta as chemistry_may_2022Meta } from '@/data/papers/chemistry-may-2022/questions'
import { questions as chemistry_may_2022_v1Questions, paperMeta as chemistry_may_2022_v1Meta } from '@/data/papers/chemistry-may-2022-v1/questions'
import { questions as chemistry_may_2022_v2Questions, paperMeta as chemistry_may_2022_v2Meta } from '@/data/papers/chemistry-may-2022-v2/questions'
import { questions as chemistry_may_2023Questions, paperMeta as chemistry_may_2023Meta } from '@/data/papers/chemistry-may-2023/questions'
import { questions as chemistry_may_2023_v1Questions, paperMeta as chemistry_may_2023_v1Meta } from '@/data/papers/chemistry-may-2023-v1/questions'
import { questions as chemistry_may_2023_v2Questions, paperMeta as chemistry_may_2023_v2Meta } from '@/data/papers/chemistry-may-2023-v2/questions'
import { questions as chemistry_may_2024Questions, paperMeta as chemistry_may_2024Meta } from '@/data/papers/chemistry-may-2024/questions'
import { questions as chemistry_may_2024_v1Questions, paperMeta as chemistry_may_2024_v1Meta } from '@/data/papers/chemistry-may-2024-v1/questions'
import { questions as chemistry_may_2024_v2Questions, paperMeta as chemistry_may_2024_v2Meta } from '@/data/papers/chemistry-may-2024-v2/questions'
import { questions as chemistry_may_2025Questions, paperMeta as chemistry_may_2025Meta } from '@/data/papers/chemistry-may-2025/questions'
import { questions as chemistry_may_2025_v1Questions, paperMeta as chemistry_may_2025_v1Meta } from '@/data/papers/chemistry-may-2025-v1/questions'
import { questions as chemistry_may_2025_v2Questions, paperMeta as chemistry_may_2025_v2Meta } from '@/data/papers/chemistry-may-2025-v2/questions'
import { questions as chemistry_nov_2016Questions, paperMeta as chemistry_nov_2016Meta } from '@/data/papers/chemistry-nov-2016/questions'
import { questions as chemistry_nov_2016_v1Questions, paperMeta as chemistry_nov_2016_v1Meta } from '@/data/papers/chemistry-nov-2016-v1/questions'
import { questions as chemistry_nov_2016_v2Questions, paperMeta as chemistry_nov_2016_v2Meta } from '@/data/papers/chemistry-nov-2016-v2/questions'
import { questions as chemistry_nov_2017Questions, paperMeta as chemistry_nov_2017Meta } from '@/data/papers/chemistry-nov-2017/questions'
import { questions as chemistry_nov_2017_v1Questions, paperMeta as chemistry_nov_2017_v1Meta } from '@/data/papers/chemistry-nov-2017-v1/questions'
import { questions as chemistry_nov_2017_v2Questions, paperMeta as chemistry_nov_2017_v2Meta } from '@/data/papers/chemistry-nov-2017-v2/questions'
import { questions as chemistry_nov_2018Questions, paperMeta as chemistry_nov_2018Meta } from '@/data/papers/chemistry-nov-2018/questions'
import { questions as chemistry_nov_2018_v1Questions, paperMeta as chemistry_nov_2018_v1Meta } from '@/data/papers/chemistry-nov-2018-v1/questions'
import { questions as chemistry_nov_2018_v2Questions, paperMeta as chemistry_nov_2018_v2Meta } from '@/data/papers/chemistry-nov-2018-v2/questions'
import { questions as chemistry_nov_2019Questions, paperMeta as chemistry_nov_2019Meta } from '@/data/papers/chemistry-nov-2019/questions'
import { questions as chemistry_nov_2019_v1Questions, paperMeta as chemistry_nov_2019_v1Meta } from '@/data/papers/chemistry-nov-2019-v1/questions'
import { questions as chemistry_nov_2019_v2Questions, paperMeta as chemistry_nov_2019_v2Meta } from '@/data/papers/chemistry-nov-2019-v2/questions'
import { questions as chemistry_nov_2020Questions, paperMeta as chemistry_nov_2020Meta } from '@/data/papers/chemistry-nov-2020/questions'
import { questions as chemistry_nov_2020_v1Questions, paperMeta as chemistry_nov_2020_v1Meta } from '@/data/papers/chemistry-nov-2020-v1/questions'
import { questions as chemistry_nov_2020_v2Questions, paperMeta as chemistry_nov_2020_v2Meta } from '@/data/papers/chemistry-nov-2020-v2/questions'
import { questions as chemistry_nov_2021Questions, paperMeta as chemistry_nov_2021Meta } from '@/data/papers/chemistry-nov-2021/questions'
import { questions as chemistry_nov_2021_v1Questions, paperMeta as chemistry_nov_2021_v1Meta } from '@/data/papers/chemistry-nov-2021-v1/questions'
import { questions as chemistry_nov_2021_v2Questions, paperMeta as chemistry_nov_2021_v2Meta } from '@/data/papers/chemistry-nov-2021-v2/questions'
import { questions as chemistry_nov_2022Questions, paperMeta as chemistry_nov_2022Meta } from '@/data/papers/chemistry-nov-2022/questions'
import { questions as chemistry_nov_2022_v1Questions, paperMeta as chemistry_nov_2022_v1Meta } from '@/data/papers/chemistry-nov-2022-v1/questions'
import { questions as chemistry_nov_2022_v2Questions, paperMeta as chemistry_nov_2022_v2Meta } from '@/data/papers/chemistry-nov-2022-v2/questions'
import { questions as chemistry_nov_2023Questions, paperMeta as chemistry_nov_2023Meta } from '@/data/papers/chemistry-nov-2023/questions'
import { questions as chemistry_nov_2023_v1Questions, paperMeta as chemistry_nov_2023_v1Meta } from '@/data/papers/chemistry-nov-2023-v1/questions'
import { questions as chemistry_nov_2023_v2Questions, paperMeta as chemistry_nov_2023_v2Meta } from '@/data/papers/chemistry-nov-2023-v2/questions'
import { questions as chemistry_nov_2024Questions, paperMeta as chemistry_nov_2024Meta } from '@/data/papers/chemistry-nov-2024/questions'
import { questions as chemistry_nov_2024_v1Questions, paperMeta as chemistry_nov_2024_v1Meta } from '@/data/papers/chemistry-nov-2024-v1/questions'
import { questions as chemistry_nov_2024_v2Questions, paperMeta as chemistry_nov_2024_v2Meta } from '@/data/papers/chemistry-nov-2024-v2/questions'
import { questions as geography_may_2021Questions, paperMeta as geography_may_2021Meta } from '@/data/papers/geography-may-2021/questions'
import { questions as geography_may_2021_v1Questions, paperMeta as geography_may_2021_v1Meta } from '@/data/papers/geography-may-2021-v1/questions'
import { questions as geography_may_2021_v2Questions, paperMeta as geography_may_2021_v2Meta } from '@/data/papers/geography-may-2021-v2/questions'
import { questions as geography_may_2022Questions, paperMeta as geography_may_2022Meta } from '@/data/papers/geography-may-2022/questions'
import { questions as geography_may_2022_v1Questions, paperMeta as geography_may_2022_v1Meta } from '@/data/papers/geography-may-2022-v1/questions'
import { questions as geography_may_2022_v2Questions, paperMeta as geography_may_2022_v2Meta } from '@/data/papers/geography-may-2022-v2/questions'
import { questions as geography_may_2023Questions, paperMeta as geography_may_2023Meta } from '@/data/papers/geography-may-2023/questions'
import { questions as geography_may_2023_v1Questions, paperMeta as geography_may_2023_v1Meta } from '@/data/papers/geography-may-2023-v1/questions'
import { questions as geography_may_2023_v2Questions, paperMeta as geography_may_2023_v2Meta } from '@/data/papers/geography-may-2023-v2/questions'
import { questions as geography_may_2024Questions, paperMeta as geography_may_2024Meta } from '@/data/papers/geography-may-2024/questions'
import { questions as geography_may_2024_v1Questions, paperMeta as geography_may_2024_v1Meta } from '@/data/papers/geography-may-2024-v1/questions'
import { questions as geography_may_2024_v2Questions, paperMeta as geography_may_2024_v2Meta } from '@/data/papers/geography-may-2024-v2/questions'
import { questions as geography_may_2025Questions, paperMeta as geography_may_2025Meta } from '@/data/papers/geography-may-2025/questions'
import { questions as geography_may_2025_v1Questions, paperMeta as geography_may_2025_v1Meta } from '@/data/papers/geography-may-2025-v1/questions'
import { questions as geography_may_2025_v2Questions, paperMeta as geography_may_2025_v2Meta } from '@/data/papers/geography-may-2025-v2/questions'
import { questions as geography_nov_2019Questions, paperMeta as geography_nov_2019Meta } from '@/data/papers/geography-nov-2019/questions'
import { questions as geography_nov_2019_v1Questions, paperMeta as geography_nov_2019_v1Meta } from '@/data/papers/geography-nov-2019-v1/questions'
import { questions as geography_nov_2019_v2Questions, paperMeta as geography_nov_2019_v2Meta } from '@/data/papers/geography-nov-2019-v2/questions'
import { questions as geography_nov_2020Questions, paperMeta as geography_nov_2020Meta } from '@/data/papers/geography-nov-2020/questions'
import { questions as geography_nov_2020_v1Questions, paperMeta as geography_nov_2020_v1Meta } from '@/data/papers/geography-nov-2020-v1/questions'
import { questions as geography_nov_2020_v2Questions, paperMeta as geography_nov_2020_v2Meta } from '@/data/papers/geography-nov-2020-v2/questions'
import { questions as geography_nov_2021Questions, paperMeta as geography_nov_2021Meta } from '@/data/papers/geography-nov-2021/questions'
import { questions as geography_nov_2021_v1Questions, paperMeta as geography_nov_2021_v1Meta } from '@/data/papers/geography-nov-2021-v1/questions'
import { questions as geography_nov_2021_v2Questions, paperMeta as geography_nov_2021_v2Meta } from '@/data/papers/geography-nov-2021-v2/questions'
import { questions as geography_nov_2022Questions, paperMeta as geography_nov_2022Meta } from '@/data/papers/geography-nov-2022/questions'
import { questions as geography_nov_2022_v1Questions, paperMeta as geography_nov_2022_v1Meta } from '@/data/papers/geography-nov-2022-v1/questions'
import { questions as geography_nov_2022_v2Questions, paperMeta as geography_nov_2022_v2Meta } from '@/data/papers/geography-nov-2022-v2/questions'
import { questions as geography_nov_2023Questions, paperMeta as geography_nov_2023Meta } from '@/data/papers/geography-nov-2023/questions'
import { questions as geography_nov_2023_v1Questions, paperMeta as geography_nov_2023_v1Meta } from '@/data/papers/geography-nov-2023-v1/questions'
import { questions as geography_nov_2023_v2Questions, paperMeta as geography_nov_2023_v2Meta } from '@/data/papers/geography-nov-2023-v2/questions'
import { questions as geography_nov_2024Questions, paperMeta as geography_nov_2024Meta } from '@/data/papers/geography-nov-2024/questions'
import { questions as geography_nov_2024_v1Questions, paperMeta as geography_nov_2024_v1Meta } from '@/data/papers/geography-nov-2024-v1/questions'
import { questions as geography_nov_2024_v2Questions, paperMeta as geography_nov_2024_v2Meta } from '@/data/papers/geography-nov-2024-v2/questions'
import { questions as humanities_may_2023Questions, paperMeta as humanities_may_2023Meta } from '@/data/papers/humanities-may-2023/questions'
import { questions as humanities_may_2023_v1Questions, paperMeta as humanities_may_2023_v1Meta } from '@/data/papers/humanities-may-2023-v1/questions'
import { questions as humanities_may_2023_v2Questions, paperMeta as humanities_may_2023_v2Meta } from '@/data/papers/humanities-may-2023-v2/questions'
import { questions as humanities_may_2024Questions, paperMeta as humanities_may_2024Meta } from '@/data/papers/humanities-may-2024/questions'
import { questions as humanities_may_2024_v1Questions, paperMeta as humanities_may_2024_v1Meta } from '@/data/papers/humanities-may-2024-v1/questions'
import { questions as humanities_may_2024_v2Questions, paperMeta as humanities_may_2024_v2Meta } from '@/data/papers/humanities-may-2024-v2/questions'
import { questions as humanities_may_2025Questions, paperMeta as humanities_may_2025Meta } from '@/data/papers/humanities-may-2025/questions'
import { questions as humanities_may_2025_v1Questions, paperMeta as humanities_may_2025_v1Meta } from '@/data/papers/humanities-may-2025-v1/questions'
import { questions as humanities_may_2025_v2Questions, paperMeta as humanities_may_2025_v2Meta } from '@/data/papers/humanities-may-2025-v2/questions'
import { questions as humanities_nov_2019Questions, paperMeta as humanities_nov_2019Meta } from '@/data/papers/humanities-nov-2019/questions'
import { questions as humanities_nov_2019_v1Questions, paperMeta as humanities_nov_2019_v1Meta } from '@/data/papers/humanities-nov-2019-v1/questions'
import { questions as humanities_nov_2019_v2Questions, paperMeta as humanities_nov_2019_v2Meta } from '@/data/papers/humanities-nov-2019-v2/questions'
import { questions as humanities_nov_2022Questions, paperMeta as humanities_nov_2022Meta } from '@/data/papers/humanities-nov-2022/questions'
import { questions as humanities_nov_2022_v1Questions, paperMeta as humanities_nov_2022_v1Meta } from '@/data/papers/humanities-nov-2022-v1/questions'
import { questions as humanities_nov_2022_v2Questions, paperMeta as humanities_nov_2022_v2Meta } from '@/data/papers/humanities-nov-2022-v2/questions'
import { questions as humanities_nov_2024Questions, paperMeta as humanities_nov_2024Meta } from '@/data/papers/humanities-nov-2024/questions'
import { questions as humanities_nov_2024_v1Questions, paperMeta as humanities_nov_2024_v1Meta } from '@/data/papers/humanities-nov-2024-v1/questions'
import { questions as humanities_nov_2024_v2Questions, paperMeta as humanities_nov_2024_v2Meta } from '@/data/papers/humanities-nov-2024-v2/questions'
import { questions as physics_may_2016Questions, paperMeta as physics_may_2016Meta } from '@/data/papers/physics-may-2016/questions'
import { questions as physics_may_2016_v1Questions, paperMeta as physics_may_2016_v1Meta } from '@/data/papers/physics-may-2016-v1/questions'
import { questions as physics_may_2016_v2Questions, paperMeta as physics_may_2016_v2Meta } from '@/data/papers/physics-may-2016-v2/questions'
import { questions as physics_may_2017Questions, paperMeta as physics_may_2017Meta } from '@/data/papers/physics-may-2017/questions'
import { questions as physics_may_2017_v1Questions, paperMeta as physics_may_2017_v1Meta } from '@/data/papers/physics-may-2017-v1/questions'
import { questions as physics_may_2017_v2Questions, paperMeta as physics_may_2017_v2Meta } from '@/data/papers/physics-may-2017-v2/questions'
import { questions as physics_may_2018Questions, paperMeta as physics_may_2018Meta } from '@/data/papers/physics-may-2018/questions'
import { questions as physics_may_2018_v1Questions, paperMeta as physics_may_2018_v1Meta } from '@/data/papers/physics-may-2018-v1/questions'
import { questions as physics_may_2018_v2Questions, paperMeta as physics_may_2018_v2Meta } from '@/data/papers/physics-may-2018-v2/questions'
import { questions as physics_may_2019Questions, paperMeta as physics_may_2019Meta } from '@/data/papers/physics-may-2019/questions'
import { questions as physics_may_2019_v1Questions, paperMeta as physics_may_2019_v1Meta } from '@/data/papers/physics-may-2019-v1/questions'
import { questions as physics_may_2019_v2Questions, paperMeta as physics_may_2019_v2Meta } from '@/data/papers/physics-may-2019-v2/questions'
import { questions as physics_may_2021Questions, paperMeta as physics_may_2021Meta } from '@/data/papers/physics-may-2021/questions'
import { questions as physics_may_2021_v1Questions, paperMeta as physics_may_2021_v1Meta } from '@/data/papers/physics-may-2021-v1/questions'
import { questions as physics_may_2021_v2Questions, paperMeta as physics_may_2021_v2Meta } from '@/data/papers/physics-may-2021-v2/questions'
import { questions as physics_may_2022Questions, paperMeta as physics_may_2022Meta } from '@/data/papers/physics-may-2022/questions'
import { questions as physics_may_2022_v1Questions, paperMeta as physics_may_2022_v1Meta } from '@/data/papers/physics-may-2022-v1/questions'
import { questions as physics_may_2022_v2Questions, paperMeta as physics_may_2022_v2Meta } from '@/data/papers/physics-may-2022-v2/questions'
import { questions as physics_may_2023Questions, paperMeta as physics_may_2023Meta } from '@/data/papers/physics-may-2023/questions'
import { questions as physics_may_2023_v1Questions, paperMeta as physics_may_2023_v1Meta } from '@/data/papers/physics-may-2023-v1/questions'
import { questions as physics_may_2023_v2Questions, paperMeta as physics_may_2023_v2Meta } from '@/data/papers/physics-may-2023-v2/questions'
import { questions as physics_may_2024Questions, paperMeta as physics_may_2024Meta } from '@/data/papers/physics-may-2024/questions'
import { questions as physics_may_2024_v1Questions, paperMeta as physics_may_2024_v1Meta } from '@/data/papers/physics-may-2024-v1/questions'
import { questions as physics_may_2024_v2Questions, paperMeta as physics_may_2024_v2Meta } from '@/data/papers/physics-may-2024-v2/questions'
import { questions as physics_may_2025Questions, paperMeta as physics_may_2025Meta } from '@/data/papers/physics-may-2025/questions'
import { questions as physics_may_2025_v1Questions, paperMeta as physics_may_2025_v1Meta } from '@/data/papers/physics-may-2025-v1/questions'
import { questions as physics_may_2025_v2Questions, paperMeta as physics_may_2025_v2Meta } from '@/data/papers/physics-may-2025-v2/questions'
import { questions as physics_nov_2016Questions, paperMeta as physics_nov_2016Meta } from '@/data/papers/physics-nov-2016/questions'
import { questions as physics_nov_2016_v1Questions, paperMeta as physics_nov_2016_v1Meta } from '@/data/papers/physics-nov-2016-v1/questions'
import { questions as physics_nov_2016_v2Questions, paperMeta as physics_nov_2016_v2Meta } from '@/data/papers/physics-nov-2016-v2/questions'
import { questions as physics_nov_2017Questions, paperMeta as physics_nov_2017Meta } from '@/data/papers/physics-nov-2017/questions'
import { questions as physics_nov_2017_v1Questions, paperMeta as physics_nov_2017_v1Meta } from '@/data/papers/physics-nov-2017-v1/questions'
import { questions as physics_nov_2017_v2Questions, paperMeta as physics_nov_2017_v2Meta } from '@/data/papers/physics-nov-2017-v2/questions'
import { questions as physics_nov_2018Questions, paperMeta as physics_nov_2018Meta } from '@/data/papers/physics-nov-2018/questions'
import { questions as physics_nov_2018_v1Questions, paperMeta as physics_nov_2018_v1Meta } from '@/data/papers/physics-nov-2018-v1/questions'
import { questions as physics_nov_2018_v2Questions, paperMeta as physics_nov_2018_v2Meta } from '@/data/papers/physics-nov-2018-v2/questions'
import { questions as physics_nov_2019Questions, paperMeta as physics_nov_2019Meta } from '@/data/papers/physics-nov-2019/questions'
import { questions as physics_nov_2019_v1Questions, paperMeta as physics_nov_2019_v1Meta } from '@/data/papers/physics-nov-2019-v1/questions'
import { questions as physics_nov_2019_v2Questions, paperMeta as physics_nov_2019_v2Meta } from '@/data/papers/physics-nov-2019-v2/questions'
import { questions as physics_nov_2020Questions, paperMeta as physics_nov_2020Meta } from '@/data/papers/physics-nov-2020/questions'
import { questions as physics_nov_2020_v1Questions, paperMeta as physics_nov_2020_v1Meta } from '@/data/papers/physics-nov-2020-v1/questions'
import { questions as physics_nov_2020_v2Questions, paperMeta as physics_nov_2020_v2Meta } from '@/data/papers/physics-nov-2020-v2/questions'
import { questions as physics_nov_2021Questions, paperMeta as physics_nov_2021Meta } from '@/data/papers/physics-nov-2021/questions'
import { questions as physics_nov_2021_v1Questions, paperMeta as physics_nov_2021_v1Meta } from '@/data/papers/physics-nov-2021-v1/questions'
import { questions as physics_nov_2021_v2Questions, paperMeta as physics_nov_2021_v2Meta } from '@/data/papers/physics-nov-2021-v2/questions'
import { questions as physics_nov_2022Questions, paperMeta as physics_nov_2022Meta } from '@/data/papers/physics-nov-2022/questions'
import { questions as physics_nov_2022_v1Questions, paperMeta as physics_nov_2022_v1Meta } from '@/data/papers/physics-nov-2022-v1/questions'
import { questions as physics_nov_2022_v2Questions, paperMeta as physics_nov_2022_v2Meta } from '@/data/papers/physics-nov-2022-v2/questions'
import { questions as physics_nov_2024Questions, paperMeta as physics_nov_2024Meta } from '@/data/papers/physics-nov-2024/questions'
import { questions as physics_nov_2024_v1Questions, paperMeta as physics_nov_2024_v1Meta } from '@/data/papers/physics-nov-2024-v1/questions'
import { questions as physics_nov_2024_v2Questions, paperMeta as physics_nov_2024_v2Meta } from '@/data/papers/physics-nov-2024-v2/questions'
import { questions as physics_practice_v1Questions, paperMeta as physics_practice_v1Meta } from '@/data/papers/physics-practice-v1/questions'
import type { Question } from '@/lib/types'

interface PageProps {
  params: { paperId: string }
}

interface PaperMeta {
  id: string
  subject: string
  session: string
  year: number
  totalMarks: number
  durationMinutes: number
  criteria: readonly string[]
}

const PAPERS: Record<string, { questions: Question[]; meta: PaperMeta }> = {
  'physics-nov-2023': { questions: physics_nov_2023Questions, meta: physics_nov_2023Meta },
  'biology-may-2016': { questions: biology_may_2016Questions, meta: biology_may_2016Meta },
  'biology-may-2017': { questions: biology_may_2017Questions, meta: biology_may_2017Meta },
  'biology-may-2018': { questions: biology_may_2018Questions, meta: biology_may_2018Meta },
  'biology-may-2019': { questions: biology_may_2019Questions, meta: biology_may_2019Meta },
  'biology-may-2021': { questions: biology_may_2021Questions, meta: biology_may_2021Meta },
  'biology-may-2022': { questions: biology_may_2022Questions, meta: biology_may_2022Meta },
  'biology-may-2023': { questions: biology_may_2023Questions, meta: biology_may_2023Meta },
  'biology-may-2024': { questions: biology_may_2024Questions, meta: biology_may_2024Meta },
  'biology-may-2025': { questions: biology_may_2025Questions, meta: biology_may_2025Meta },
  'biology-may-2025-v1': { questions: biology_may_2025_v1Questions, meta: biology_may_2025_v1Meta },
  'biology-may-2025-v2': { questions: biology_may_2025_v2Questions, meta: biology_may_2025_v2Meta },
  'biology-nov-2016': { questions: biology_nov_2016Questions, meta: biology_nov_2016Meta },
  'biology-nov-2017': { questions: biology_nov_2017Questions, meta: biology_nov_2017Meta },
  'biology-nov-2018': { questions: biology_nov_2018Questions, meta: biology_nov_2018Meta },
  'biology-nov-2019': { questions: biology_nov_2019Questions, meta: biology_nov_2019Meta },
  'biology-nov-2020': { questions: biology_nov_2020Questions, meta: biology_nov_2020Meta },
  'biology-nov-2021': { questions: biology_nov_2021Questions, meta: biology_nov_2021Meta },
  'biology-nov-2022': { questions: biology_nov_2022Questions, meta: biology_nov_2022Meta },
  'biology-nov-2023': { questions: biology_nov_2023Questions, meta: biology_nov_2023Meta },
  'biology-nov-2024': { questions: biology_nov_2024Questions, meta: biology_nov_2024Meta },
  'chemistry-may-2016': { questions: chemistry_may_2016Questions, meta: chemistry_may_2016Meta },
  'chemistry-may-2016-v1': { questions: chemistry_may_2016_v1Questions, meta: chemistry_may_2016_v1Meta },
  'chemistry-may-2016-v2': { questions: chemistry_may_2016_v2Questions, meta: chemistry_may_2016_v2Meta },
  'chemistry-may-2017': { questions: chemistry_may_2017Questions, meta: chemistry_may_2017Meta },
  'chemistry-may-2017-v1': { questions: chemistry_may_2017_v1Questions, meta: chemistry_may_2017_v1Meta },
  'chemistry-may-2017-v2': { questions: chemistry_may_2017_v2Questions, meta: chemistry_may_2017_v2Meta },
  'chemistry-may-2018': { questions: chemistry_may_2018Questions, meta: chemistry_may_2018Meta },
  'chemistry-may-2018-v1': { questions: chemistry_may_2018_v1Questions, meta: chemistry_may_2018_v1Meta },
  'chemistry-may-2018-v2': { questions: chemistry_may_2018_v2Questions, meta: chemistry_may_2018_v2Meta },
  'chemistry-may-2019': { questions: chemistry_may_2019Questions, meta: chemistry_may_2019Meta },
  'chemistry-may-2019-v1': { questions: chemistry_may_2019_v1Questions, meta: chemistry_may_2019_v1Meta },
  'chemistry-may-2019-v2': { questions: chemistry_may_2019_v2Questions, meta: chemistry_may_2019_v2Meta },
  'chemistry-may-2021': { questions: chemistry_may_2021Questions, meta: chemistry_may_2021Meta },
  'chemistry-may-2021-v1': { questions: chemistry_may_2021_v1Questions, meta: chemistry_may_2021_v1Meta },
  'chemistry-may-2021-v2': { questions: chemistry_may_2021_v2Questions, meta: chemistry_may_2021_v2Meta },
  'chemistry-may-2022': { questions: chemistry_may_2022Questions, meta: chemistry_may_2022Meta },
  'chemistry-may-2022-v1': { questions: chemistry_may_2022_v1Questions, meta: chemistry_may_2022_v1Meta },
  'chemistry-may-2022-v2': { questions: chemistry_may_2022_v2Questions, meta: chemistry_may_2022_v2Meta },
  'chemistry-may-2023': { questions: chemistry_may_2023Questions, meta: chemistry_may_2023Meta },
  'chemistry-may-2023-v1': { questions: chemistry_may_2023_v1Questions, meta: chemistry_may_2023_v1Meta },
  'chemistry-may-2023-v2': { questions: chemistry_may_2023_v2Questions, meta: chemistry_may_2023_v2Meta },
  'chemistry-may-2024': { questions: chemistry_may_2024Questions, meta: chemistry_may_2024Meta },
  'chemistry-may-2024-v1': { questions: chemistry_may_2024_v1Questions, meta: chemistry_may_2024_v1Meta },
  'chemistry-may-2024-v2': { questions: chemistry_may_2024_v2Questions, meta: chemistry_may_2024_v2Meta },
  'chemistry-may-2025': { questions: chemistry_may_2025Questions, meta: chemistry_may_2025Meta },
  'chemistry-may-2025-v1': { questions: chemistry_may_2025_v1Questions, meta: chemistry_may_2025_v1Meta },
  'chemistry-may-2025-v2': { questions: chemistry_may_2025_v2Questions, meta: chemistry_may_2025_v2Meta },
  'chemistry-nov-2016': { questions: chemistry_nov_2016Questions, meta: chemistry_nov_2016Meta },
  'chemistry-nov-2016-v1': { questions: chemistry_nov_2016_v1Questions, meta: chemistry_nov_2016_v1Meta },
  'chemistry-nov-2016-v2': { questions: chemistry_nov_2016_v2Questions, meta: chemistry_nov_2016_v2Meta },
  'chemistry-nov-2017': { questions: chemistry_nov_2017Questions, meta: chemistry_nov_2017Meta },
  'chemistry-nov-2017-v1': { questions: chemistry_nov_2017_v1Questions, meta: chemistry_nov_2017_v1Meta },
  'chemistry-nov-2017-v2': { questions: chemistry_nov_2017_v2Questions, meta: chemistry_nov_2017_v2Meta },
  'chemistry-nov-2018': { questions: chemistry_nov_2018Questions, meta: chemistry_nov_2018Meta },
  'chemistry-nov-2018-v1': { questions: chemistry_nov_2018_v1Questions, meta: chemistry_nov_2018_v1Meta },
  'chemistry-nov-2018-v2': { questions: chemistry_nov_2018_v2Questions, meta: chemistry_nov_2018_v2Meta },
  'chemistry-nov-2019': { questions: chemistry_nov_2019Questions, meta: chemistry_nov_2019Meta },
  'chemistry-nov-2019-v1': { questions: chemistry_nov_2019_v1Questions, meta: chemistry_nov_2019_v1Meta },
  'chemistry-nov-2019-v2': { questions: chemistry_nov_2019_v2Questions, meta: chemistry_nov_2019_v2Meta },
  'chemistry-nov-2020': { questions: chemistry_nov_2020Questions, meta: chemistry_nov_2020Meta },
  'chemistry-nov-2020-v1': { questions: chemistry_nov_2020_v1Questions, meta: chemistry_nov_2020_v1Meta },
  'chemistry-nov-2020-v2': { questions: chemistry_nov_2020_v2Questions, meta: chemistry_nov_2020_v2Meta },
  'chemistry-nov-2021': { questions: chemistry_nov_2021Questions, meta: chemistry_nov_2021Meta },
  'chemistry-nov-2021-v1': { questions: chemistry_nov_2021_v1Questions, meta: chemistry_nov_2021_v1Meta },
  'chemistry-nov-2021-v2': { questions: chemistry_nov_2021_v2Questions, meta: chemistry_nov_2021_v2Meta },
  'chemistry-nov-2022': { questions: chemistry_nov_2022Questions, meta: chemistry_nov_2022Meta },
  'chemistry-nov-2022-v1': { questions: chemistry_nov_2022_v1Questions, meta: chemistry_nov_2022_v1Meta },
  'chemistry-nov-2022-v2': { questions: chemistry_nov_2022_v2Questions, meta: chemistry_nov_2022_v2Meta },
  'chemistry-nov-2023': { questions: chemistry_nov_2023Questions, meta: chemistry_nov_2023Meta },
  'chemistry-nov-2023-v1': { questions: chemistry_nov_2023_v1Questions, meta: chemistry_nov_2023_v1Meta },
  'chemistry-nov-2023-v2': { questions: chemistry_nov_2023_v2Questions, meta: chemistry_nov_2023_v2Meta },
  'chemistry-nov-2024': { questions: chemistry_nov_2024Questions, meta: chemistry_nov_2024Meta },
  'chemistry-nov-2024-v1': { questions: chemistry_nov_2024_v1Questions, meta: chemistry_nov_2024_v1Meta },
  'chemistry-nov-2024-v2': { questions: chemistry_nov_2024_v2Questions, meta: chemistry_nov_2024_v2Meta },
  'geography-may-2021': { questions: geography_may_2021Questions, meta: geography_may_2021Meta },
  'geography-may-2021-v1': { questions: geography_may_2021_v1Questions, meta: geography_may_2021_v1Meta },
  'geography-may-2021-v2': { questions: geography_may_2021_v2Questions, meta: geography_may_2021_v2Meta },
  'geography-may-2022': { questions: geography_may_2022Questions, meta: geography_may_2022Meta },
  'geography-may-2022-v1': { questions: geography_may_2022_v1Questions, meta: geography_may_2022_v1Meta },
  'geography-may-2022-v2': { questions: geography_may_2022_v2Questions, meta: geography_may_2022_v2Meta },
  'geography-may-2023': { questions: geography_may_2023Questions, meta: geography_may_2023Meta },
  'geography-may-2023-v1': { questions: geography_may_2023_v1Questions, meta: geography_may_2023_v1Meta },
  'geography-may-2023-v2': { questions: geography_may_2023_v2Questions, meta: geography_may_2023_v2Meta },
  'geography-may-2024': { questions: geography_may_2024Questions, meta: geography_may_2024Meta },
  'geography-may-2024-v1': { questions: geography_may_2024_v1Questions, meta: geography_may_2024_v1Meta },
  'geography-may-2024-v2': { questions: geography_may_2024_v2Questions, meta: geography_may_2024_v2Meta },
  'geography-may-2025': { questions: geography_may_2025Questions, meta: geography_may_2025Meta },
  'geography-may-2025-v1': { questions: geography_may_2025_v1Questions, meta: geography_may_2025_v1Meta },
  'geography-may-2025-v2': { questions: geography_may_2025_v2Questions, meta: geography_may_2025_v2Meta },
  'geography-nov-2019': { questions: geography_nov_2019Questions, meta: geography_nov_2019Meta },
  'geography-nov-2019-v1': { questions: geography_nov_2019_v1Questions, meta: geography_nov_2019_v1Meta },
  'geography-nov-2019-v2': { questions: geography_nov_2019_v2Questions, meta: geography_nov_2019_v2Meta },
  'geography-nov-2020': { questions: geography_nov_2020Questions, meta: geography_nov_2020Meta },
  'geography-nov-2020-v1': { questions: geography_nov_2020_v1Questions, meta: geography_nov_2020_v1Meta },
  'geography-nov-2020-v2': { questions: geography_nov_2020_v2Questions, meta: geography_nov_2020_v2Meta },
  'geography-nov-2021': { questions: geography_nov_2021Questions, meta: geography_nov_2021Meta },
  'geography-nov-2021-v1': { questions: geography_nov_2021_v1Questions, meta: geography_nov_2021_v1Meta },
  'geography-nov-2021-v2': { questions: geography_nov_2021_v2Questions, meta: geography_nov_2021_v2Meta },
  'geography-nov-2022': { questions: geography_nov_2022Questions, meta: geography_nov_2022Meta },
  'geography-nov-2022-v1': { questions: geography_nov_2022_v1Questions, meta: geography_nov_2022_v1Meta },
  'geography-nov-2022-v2': { questions: geography_nov_2022_v2Questions, meta: geography_nov_2022_v2Meta },
  'geography-nov-2023': { questions: geography_nov_2023Questions, meta: geography_nov_2023Meta },
  'geography-nov-2023-v1': { questions: geography_nov_2023_v1Questions, meta: geography_nov_2023_v1Meta },
  'geography-nov-2023-v2': { questions: geography_nov_2023_v2Questions, meta: geography_nov_2023_v2Meta },
  'geography-nov-2024': { questions: geography_nov_2024Questions, meta: geography_nov_2024Meta },
  'geography-nov-2024-v1': { questions: geography_nov_2024_v1Questions, meta: geography_nov_2024_v1Meta },
  'geography-nov-2024-v2': { questions: geography_nov_2024_v2Questions, meta: geography_nov_2024_v2Meta },
  'humanities-may-2023': { questions: humanities_may_2023Questions, meta: humanities_may_2023Meta },
  'humanities-may-2023-v1': { questions: humanities_may_2023_v1Questions, meta: humanities_may_2023_v1Meta },
  'humanities-may-2023-v2': { questions: humanities_may_2023_v2Questions, meta: humanities_may_2023_v2Meta },
  'humanities-may-2024': { questions: humanities_may_2024Questions, meta: humanities_may_2024Meta },
  'humanities-may-2024-v1': { questions: humanities_may_2024_v1Questions, meta: humanities_may_2024_v1Meta },
  'humanities-may-2024-v2': { questions: humanities_may_2024_v2Questions, meta: humanities_may_2024_v2Meta },
  'humanities-may-2025': { questions: humanities_may_2025Questions, meta: humanities_may_2025Meta },
  'humanities-may-2025-v1': { questions: humanities_may_2025_v1Questions, meta: humanities_may_2025_v1Meta },
  'humanities-may-2025-v2': { questions: humanities_may_2025_v2Questions, meta: humanities_may_2025_v2Meta },
  'humanities-nov-2019': { questions: humanities_nov_2019Questions, meta: humanities_nov_2019Meta },
  'humanities-nov-2019-v1': { questions: humanities_nov_2019_v1Questions, meta: humanities_nov_2019_v1Meta },
  'humanities-nov-2019-v2': { questions: humanities_nov_2019_v2Questions, meta: humanities_nov_2019_v2Meta },
  'humanities-nov-2022': { questions: humanities_nov_2022Questions, meta: humanities_nov_2022Meta },
  'humanities-nov-2022-v1': { questions: humanities_nov_2022_v1Questions, meta: humanities_nov_2022_v1Meta },
  'humanities-nov-2022-v2': { questions: humanities_nov_2022_v2Questions, meta: humanities_nov_2022_v2Meta },
  'humanities-nov-2024': { questions: humanities_nov_2024Questions, meta: humanities_nov_2024Meta },
  'humanities-nov-2024-v1': { questions: humanities_nov_2024_v1Questions, meta: humanities_nov_2024_v1Meta },
  'humanities-nov-2024-v2': { questions: humanities_nov_2024_v2Questions, meta: humanities_nov_2024_v2Meta },
  'physics-may-2016': { questions: physics_may_2016Questions, meta: physics_may_2016Meta },
  'physics-may-2016-v1': { questions: physics_may_2016_v1Questions, meta: physics_may_2016_v1Meta },
  'physics-may-2016-v2': { questions: physics_may_2016_v2Questions, meta: physics_may_2016_v2Meta },
  'physics-may-2017': { questions: physics_may_2017Questions, meta: physics_may_2017Meta },
  'physics-may-2017-v1': { questions: physics_may_2017_v1Questions, meta: physics_may_2017_v1Meta },
  'physics-may-2017-v2': { questions: physics_may_2017_v2Questions, meta: physics_may_2017_v2Meta },
  'physics-may-2018': { questions: physics_may_2018Questions, meta: physics_may_2018Meta },
  'physics-may-2018-v1': { questions: physics_may_2018_v1Questions, meta: physics_may_2018_v1Meta },
  'physics-may-2018-v2': { questions: physics_may_2018_v2Questions, meta: physics_may_2018_v2Meta },
  'physics-may-2019': { questions: physics_may_2019Questions, meta: physics_may_2019Meta },
  'physics-may-2019-v1': { questions: physics_may_2019_v1Questions, meta: physics_may_2019_v1Meta },
  'physics-may-2019-v2': { questions: physics_may_2019_v2Questions, meta: physics_may_2019_v2Meta },
  'physics-may-2021': { questions: physics_may_2021Questions, meta: physics_may_2021Meta },
  'physics-may-2021-v1': { questions: physics_may_2021_v1Questions, meta: physics_may_2021_v1Meta },
  'physics-may-2021-v2': { questions: physics_may_2021_v2Questions, meta: physics_may_2021_v2Meta },
  'physics-may-2022': { questions: physics_may_2022Questions, meta: physics_may_2022Meta },
  'physics-may-2022-v1': { questions: physics_may_2022_v1Questions, meta: physics_may_2022_v1Meta },
  'physics-may-2022-v2': { questions: physics_may_2022_v2Questions, meta: physics_may_2022_v2Meta },
  'physics-may-2023': { questions: physics_may_2023Questions, meta: physics_may_2023Meta },
  'physics-may-2023-v1': { questions: physics_may_2023_v1Questions, meta: physics_may_2023_v1Meta },
  'physics-may-2023-v2': { questions: physics_may_2023_v2Questions, meta: physics_may_2023_v2Meta },
  'physics-may-2024': { questions: physics_may_2024Questions, meta: physics_may_2024Meta },
  'physics-may-2024-v1': { questions: physics_may_2024_v1Questions, meta: physics_may_2024_v1Meta },
  'physics-may-2024-v2': { questions: physics_may_2024_v2Questions, meta: physics_may_2024_v2Meta },
  'physics-may-2025': { questions: physics_may_2025Questions, meta: physics_may_2025Meta },
  'physics-may-2025-v1': { questions: physics_may_2025_v1Questions, meta: physics_may_2025_v1Meta },
  'physics-may-2025-v2': { questions: physics_may_2025_v2Questions, meta: physics_may_2025_v2Meta },
  'physics-nov-2016': { questions: physics_nov_2016Questions, meta: physics_nov_2016Meta },
  'physics-nov-2016-v1': { questions: physics_nov_2016_v1Questions, meta: physics_nov_2016_v1Meta },
  'physics-nov-2016-v2': { questions: physics_nov_2016_v2Questions, meta: physics_nov_2016_v2Meta },
  'physics-nov-2017': { questions: physics_nov_2017Questions, meta: physics_nov_2017Meta },
  'physics-nov-2017-v1': { questions: physics_nov_2017_v1Questions, meta: physics_nov_2017_v1Meta },
  'physics-nov-2017-v2': { questions: physics_nov_2017_v2Questions, meta: physics_nov_2017_v2Meta },
  'physics-nov-2018': { questions: physics_nov_2018Questions, meta: physics_nov_2018Meta },
  'physics-nov-2018-v1': { questions: physics_nov_2018_v1Questions, meta: physics_nov_2018_v1Meta },
  'physics-nov-2018-v2': { questions: physics_nov_2018_v2Questions, meta: physics_nov_2018_v2Meta },
  'physics-nov-2019': { questions: physics_nov_2019Questions, meta: physics_nov_2019Meta },
  'physics-nov-2019-v1': { questions: physics_nov_2019_v1Questions, meta: physics_nov_2019_v1Meta },
  'physics-nov-2019-v2': { questions: physics_nov_2019_v2Questions, meta: physics_nov_2019_v2Meta },
  'physics-nov-2020': { questions: physics_nov_2020Questions, meta: physics_nov_2020Meta },
  'physics-nov-2020-v1': { questions: physics_nov_2020_v1Questions, meta: physics_nov_2020_v1Meta },
  'physics-nov-2020-v2': { questions: physics_nov_2020_v2Questions, meta: physics_nov_2020_v2Meta },
  'physics-nov-2021': { questions: physics_nov_2021Questions, meta: physics_nov_2021Meta },
  'physics-nov-2021-v1': { questions: physics_nov_2021_v1Questions, meta: physics_nov_2021_v1Meta },
  'physics-nov-2021-v2': { questions: physics_nov_2021_v2Questions, meta: physics_nov_2021_v2Meta },
  'physics-nov-2022': { questions: physics_nov_2022Questions, meta: physics_nov_2022Meta },
  'physics-nov-2022-v1': { questions: physics_nov_2022_v1Questions, meta: physics_nov_2022_v1Meta },
  'physics-nov-2022-v2': { questions: physics_nov_2022_v2Questions, meta: physics_nov_2022_v2Meta },
  'physics-nov-2024': { questions: physics_nov_2024Questions, meta: physics_nov_2024Meta },
  'physics-nov-2024-v1': { questions: physics_nov_2024_v1Questions, meta: physics_nov_2024_v1Meta },
  'physics-nov-2024-v2': { questions: physics_nov_2024_v2Questions, meta: physics_nov_2024_v2Meta },
  'physics-practice-v1': { questions: physics_practice_v1Questions, meta: physics_practice_v1Meta },
}

export default function ExamPage({ params }: PageProps) {
  const { paperId } = params
  const paper = PAPERS[paperId]

  if (!paper) {
    notFound()
  }

  return <ExamShell questions={paper.questions} paperId={paperId} />
}
