import 'server-only'
/**
 * AUTO-GENERATED by scripts/update-registries.js — do not edit manually.
 * Run: node scripts/update-registries.js
 *
 * Maps paperId → MS record so the marking engine can grade any paper.
 */
import type { MSRecord } from '@/data/papers/physics-nov-2023/markscheme'
export type { MSRecord }

import { MS as MS_physics_nov_2023 } from '@/data/papers/physics-nov-2023/markscheme'
import { MS as MS_physics_may_2016 } from '@/data/papers/physics-may-2016/markscheme'
import { MS as MS_physics_may_2017 } from '@/data/papers/physics-may-2017/markscheme'
import { MS as MS_physics_may_2018 } from '@/data/papers/physics-may-2018/markscheme'
import { MS as MS_physics_may_2019 } from '@/data/papers/physics-may-2019/markscheme'
import { MS as MS_physics_may_2021 } from '@/data/papers/physics-may-2021/markscheme'
import { MS as MS_physics_may_2022 } from '@/data/papers/physics-may-2022/markscheme'
import { MS as MS_physics_may_2023 } from '@/data/papers/physics-may-2023/markscheme'
import { MS as MS_physics_may_2024 } from '@/data/papers/physics-may-2024/markscheme'
import { MS as MS_physics_may_2025 } from '@/data/papers/physics-may-2025/markscheme'
import { MS as MS_physics_nov_2016 } from '@/data/papers/physics-nov-2016/markscheme'
import { MS as MS_physics_nov_2017 } from '@/data/papers/physics-nov-2017/markscheme'
import { MS as MS_physics_nov_2018 } from '@/data/papers/physics-nov-2018/markscheme'
import { MS as MS_physics_nov_2019 } from '@/data/papers/physics-nov-2019/markscheme'
import { MS as MS_physics_nov_2020 } from '@/data/papers/physics-nov-2020/markscheme'
import { MS as MS_physics_nov_2021 } from '@/data/papers/physics-nov-2021/markscheme'
import { MS as MS_physics_nov_2022 } from '@/data/papers/physics-nov-2022/markscheme'
import { MS as MS_physics_nov_2024 } from '@/data/papers/physics-nov-2024/markscheme'
import { MS as MS_biology_may_2025 } from '@/data/papers/biology-may-2025/markscheme'

const _registry: Record<string, Record<string, MSRecord>> = {
  'physics-nov-2023': MS_physics_nov_2023,
  'physics-may-2016': MS_physics_may_2016,
  'physics-may-2017': MS_physics_may_2017,
  'physics-may-2018': MS_physics_may_2018,
  'physics-may-2019': MS_physics_may_2019,
  'physics-may-2021': MS_physics_may_2021,
  'physics-may-2022': MS_physics_may_2022,
  'physics-may-2023': MS_physics_may_2023,
  'physics-may-2024': MS_physics_may_2024,
  'physics-may-2025': MS_physics_may_2025,
  'physics-nov-2016': MS_physics_nov_2016,
  'physics-nov-2017': MS_physics_nov_2017,
  'physics-nov-2018': MS_physics_nov_2018,
  'physics-nov-2019': MS_physics_nov_2019,
  'physics-nov-2020': MS_physics_nov_2020,
  'physics-nov-2021': MS_physics_nov_2021,
  'physics-nov-2022': MS_physics_nov_2022,
  'physics-nov-2024': MS_physics_nov_2024,
  'biology-may-2025': MS_biology_may_2025,
  // Add new papers by running: node scripts/update-registries.js
}

/**
 * Get the mark scheme record for a given paper.
 * Falls back to physics-nov-2023 if paperId not found (legacy behaviour).
 */
export function getMSForPaper(paperId: string): Record<string, MSRecord> {
  return _registry[paperId] ?? MS_physics_nov_2023
}
