import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import PapersGrid from '@/components/papers/PapersGrid'

interface Paper {
  id: string
  subject: string
  session: string
  year: number
  total_marks: number
  duration_minutes: number
  is_published: boolean
}

interface AttemptRow {
  paper_id: string
  status: string
}

export default async function PapersPage() {
  const supabase = createClient()

  const { data: { session } } = await supabase.auth.getSession()
  if (!session) redirect('/login')

  const [papersRes, attemptsRes] = await Promise.all([
    supabase
      .from('papers')
      .select('id, subject, session, year, total_marks, duration_minutes, is_published')
      .eq('is_published', true)
      .order('year', { ascending: false }),

    supabase
      .from('attempts')
      .select('paper_id, status')
      .eq('user_id', session.user.id),
  ])

  const papers: Paper[] = papersRes.data ?? []

  // Override Supabase values with local paper metadata (source of truth)
  // AUTO-GENERATED by scripts/update-registries.js — do not edit manually.
  const LOCAL_PAPER_META: Record<string, Partial<Paper>> = {
    'physics-may-2016': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2017': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2018': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2019': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2021': { total_marks: 98, duration_minutes: 90 },
    'physics-may-2022': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2023': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2024': { total_marks: 100, duration_minutes: 90 },
    'physics-may-2025': { total_marks: 100, duration_minutes: 90 },
    'physics-nov-2016': { total_marks: 120, duration_minutes: 120 },
    'physics-nov-2017': { total_marks: 100, duration_minutes: 90 },
    'physics-nov-2018': { total_marks: 100, duration_minutes: 90 },
    'physics-nov-2019': { total_marks: 99, duration_minutes: 90 },
    'physics-nov-2020': { total_marks: 100, duration_minutes: 90 },
    'physics-nov-2021': { total_marks: 98, duration_minutes: 90 },
    'physics-nov-2022': { total_marks: 100, duration_minutes: 90 },
    'physics-nov-2023': { total_marks: 100, duration_minutes: 90 },
    'physics-nov-2024': { total_marks: 100, duration_minutes: 90 },
    'physics-practice-v1': { total_marks: 85, duration_minutes: 90 },
  }
  const papersWithMeta = papers.map(p => ({ ...p, ...(LOCAL_PAPER_META[p.id] ?? {}) }))

  const attempts: AttemptRow[] = attemptsRes.data ?? []

  const completedPapers = new Set(
    attempts.filter((a) => a.status === 'completed').map((a) => a.paper_id)
  )
  const inProgressPapers = new Set(
    attempts.filter((a) => a.status === 'in_progress').map((a) => a.paper_id)
  )

  const subjects = Array.from(new Set(papersWithMeta.map((p) => p.subject)))

  return (
    <div className="max-w-6xl mx-auto px-4 py-10">

      {/* ── Page header ── */}
      <div className="mb-8 fade-up">
        <p
          className="text-xs font-bold uppercase tracking-widest mb-1"
          style={{ color: '#547ca4' }}
        >
          IB MYP Sciences
        </p>
        <h1
          className="text-3xl md:text-4xl font-extrabold leading-tight"
          style={{ color: '#1f3674' }}
        >
          Practice Papers
        </h1>
        <p className="mt-2 text-sm" style={{ color: '#547ca4' }}>
          Attempt past IB MYP Sciences papers with AI-powered grading and instant feedback.
        </p>
      </div>

      {/* ── Subject filter pills ── */}
      {subjects.length > 0 && (
        <div className="flex flex-wrap items-center gap-2 mb-8 fade-up" style={{ animationDelay: '0.05s' }}>
          <span
            className="text-xs font-bold uppercase tracking-widest mr-1"
            style={{ color: '#274e68' }}
          >
            Subjects:
          </span>
          {subjects.map((subject) => (
            <span
              key={subject}
              className="px-3 py-1 rounded-full text-xs font-bold"
              style={{
                background: '#1f3674',
                color: '#adf1c4',
                letterSpacing: '0.04em',
              }}
            >
              {subject}
            </span>
          ))}
        </div>
      )}

      {/* ── Animated papers grid (client component) ── */}
      <PapersGrid
        papers={papersWithMeta}
        completedPapers={completedPapers}
        inProgressPapers={inProgressPapers}
      />
    </div>
  )
}
