import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background:    "var(--background)",
        foreground:    "var(--foreground)",
        "brand-navy":  "var(--brand-navy)",
        "brand-red":   "var(--brand-red)",
        "brand-steel": "var(--brand-steel)",
        "brand-dark":  "var(--brand-dark)",
        "brand-mint":  "var(--brand-mint)",
        /* legacy aliases */
        "ib-blue":   "var(--ib-blue)",
        "ib-teal":   "var(--ib-teal)",
        "ib-teal-l": "var(--ib-teal-l)",
        "ib-green":  "var(--ib-green)",
        "ib-amber":  "var(--ib-amber)",
        "ib-red":    "var(--ib-red)",

        /* ── Atlas semantic theme tokens (data-theme switched) ── */
        bg:                 "var(--bg)",
        surface:            "var(--surface)",
        "surface-2":        "var(--surface-2)",
        "surface-3":        "var(--surface-3)",
        "surface-elevated": "var(--surface-elevated)",
        "surface-inset":    "var(--surface-inset)",
        "surface-tint":     "var(--surface-tint)",
        "surface-deep":     "var(--surface-deep)",
        line:               "var(--border)",
        "line-strong":      "var(--border-strong)",
        divider:            "var(--divider)",
        ink:                "var(--text)",
        "ink-muted":        "var(--text-muted)",
        "ink-subtle":       "var(--text-subtle)",
        "on-accent":        "var(--text-on-accent)",
        accent:             "var(--accent)",
        "accent-hover":     "var(--accent-hover)",
        "accent-fg":        "var(--accent-fg)",
        "accent-soft":      "var(--accent-soft)",
        "accent-2":         "var(--accent-2)",
        action:             "var(--accent-action)",
        "action-hover":     "var(--accent-action-hover)",
        success:            "var(--success)",
        "success-surface":  "var(--success-surface)",
        warning:            "var(--warning)",
        "warning-surface":  "var(--warning-surface)",
        danger:             "var(--danger)",
        "danger-surface":   "var(--danger-surface)",
        info:               "var(--info)",
        "info-surface":     "var(--info-surface)",
        cA: "var(--cA)", cB: "var(--cB)", cC: "var(--cC)", cD: "var(--cD)",
      },
      borderRadius: {
        card:    "var(--radius-card)",
        panel:   "var(--radius-panel)",
        control: "var(--radius-control)",
        pill:    "var(--radius-pill)",
      },
      boxShadow: {
        card:        "var(--shadow-card)",
        "card-hover":"var(--shadow-card-hover)",
        elevated:    "var(--shadow-elevated)",
        nav:         "var(--shadow-nav)",
      },
      fontFamily: {
        sans:    ["var(--font-source-sans)", "Arial", "Helvetica", "sans-serif"],
        mono:    ["var(--font-jetbrains-mono)", "'Courier New'", "monospace"],
        display: ["var(--font-display)", "Arial", "Helvetica", "sans-serif"],
        body:    ["var(--font-body)", "Arial", "Helvetica", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
